@startuml
start

:Вход в приложение;
:Выбор темы;

if (Нужна теория?) then (да)
  :Изучение теории;
endif

:Прохождение теста;
:Получение результатов;

if (Посмотреть статистику?) then (да)
  :Анализ статистики;
endif

if (Повторить?) then (да)
  -> [yes] :Выбор темы;
  -down-> :Прохождение теста;
else
  -> [no] stop
endif

@enduml
