@startuml
[*] --> Ожидание_старта

Ожидание_старта --> В_процессе : начать тест
В_процессе --> Завершён : завершить тест
Завершён --> Показ_результата : показать результат
Показ_результата --> В_процессе : повторить
Показ_результата --> [*]

@enduml
