@startuml
left to right direction
actor User

rectangle "Интерактивное приложение" {
    User --> (Регистрация / Вход)
    User --> (Просмотр теории)
    User --> (Прохождение тестов)
    User --> (Получение результатов)
    User --> (Просмотр статистики)
    User --> (Повторное прохождение темы)
}

@enduml
